/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apppmymc.utilities;

import apppmymc.ParDispersion;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author JamesCarrillo
 */
public class FrmLineas extends javax.swing.JFrame {

    /**
     * Creates new form FrmLineas
     */
    private List<ParDispersion> list = new ArrayList<>();

    public FrmLineas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void cargarLista() {
        ParDispersion par0 = new ParDispersion(0.872, 0.219);
        ParDispersion par1 = new ParDispersion(0.219, 0.570);
        ParDispersion par2 = new ParDispersion(0.570, 0.618);
        ParDispersion par3 = new ParDispersion(0.618, 0.291);
        ParDispersion par4 = new ParDispersion(0.291, 0.913);
        ParDispersion par5 = new ParDispersion(0.913, 0.950);
        ParDispersion par6 = new ParDispersion(0.950, 0.041);
        ParDispersion par7 = new ParDispersion(0.041, 0.842);
        ParDispersion par8 = new ParDispersion(0.842, 0.512);
        ParDispersion par9 = new ParDispersion(0.512, 0.151);
        list.add(par0);
        list.add(par1);
        list.add(par2);
        list.add(par3);
        list.add(par4);
        list.add(par5);
        list.add(par6);
        list.add(par7);
        list.add(par8);
        list.add(par9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnDibujar = new javax.swing.JButton();
        panelPlano = new javax.swing.JPanel();
        txtN = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDibujar.setText("DIBUJAR");
        btnDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDibujarActionPerformed(evt);
            }
        });

        panelPlano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelPlanoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelPlanoLayout = new javax.swing.GroupLayout(panelPlano);
        panelPlano.setLayout(panelPlanoLayout);
        panelPlanoLayout.setHorizontalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        panelPlanoLayout.setVerticalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnDibujar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDibujar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDibujarActionPerformed
        // TODO add your handling code here:

        this.panelPlano.getGraphics().clearRect(0, 0, this.panelPlano.getWidth(), this.panelPlano.getHeight());
        DiagramaDispercion diagrama = new DiagramaDispercion(this.panelPlano.getGraphics(), new Dimension(400, 300), 60, Integer.parseInt(txtN.getText().trim()), list);
        diagrama.construir();
        /*
        Graphics g = this.panelPlano.getGraphics();
        g.drawLine(30, 200, 400 + 30, 200);
        g.drawLine(30, 0, 30, 200);
         */
    }//GEN-LAST:event_btnDibujarActionPerformed

    private void panelPlanoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlanoMousePressed
        // TODO add your handling code here:
        Graphics g = this.panelPlano.getGraphics();
        //g.drawRect(evt.getX(), evt.getY(), 7, 7);
        g.drawOval(evt.getX(), evt.getY(), 7, 7);
        //g.drawString("JAMES", evt.getX(), evt.getY());
    }//GEN-LAST:event_panelPlanoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLineas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDibujar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelPlano;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
